development:
  adapter: async

test:
  adapter: test

production:
  adapter: async # 追記
  # adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: original_app_production
